import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Header, Footer} from "./components"

const magnifico = localFont({
  src: './fonts/Magnifico.ttf',  
  variable: '--font-magnifico',   
  weight: '400',                    
  style: 'normal',                  
  display: 'swap',                  
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${magnifico.variable} ${geistMono.variable} antialiased`}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
